---
name: Terraform Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
    - name: Run terraform validate
      run: terraform validate
      env:
        NOMAD_ADDR: keepNomadProviderHappy
...